// Fun facts and info about each Eurovision country
const COUNTRY_INFO = {
  sweden: {
    capital: 'Stockholm',
    population: '10.5M',
    eurovisionWins: 7,
    firstEntry: 1958,
    funFact: 'Sweden has the most Eurovision wins after Ireland, including ABBA\'s legendary "Waterloo" in 1974.',
    famousActs: ['ABBA', 'Loreen', 'Måns Zelmerlöw'],
  },
  italy: {
    capital: 'Rome',
    population: '59M',
    eurovisionWins: 3,
    firstEntry: 1956,
    funFact: 'Italy was one of the 7 founding countries of the Eurovision Song Contest in 1956.',
    famousActs: ['Måneskin', 'Domenico Modugno', 'Gigliola Cinquetti'],
  },
  ukraine: {
    capital: 'Kyiv',
    population: '44M',
    eurovisionWins: 3,
    firstEntry: 2003,
    funFact: 'Ukraine won Eurovision in its debut decade and has never finished last in a final.',
    famousActs: ['Kalush Orchestra', 'Jamala', 'Ruslana'],
  },
  france: {
    capital: 'Paris',
    population: '68M',
    eurovisionWins: 5,
    firstEntry: 1956,
    funFact: 'France is a founding member and one of the "Big Five" automatic finalists.',
    famousActs: ['Marie Myriam', 'Frida Boccara', 'Barbara Pravi'],
  },
  norway: {
    capital: 'Oslo',
    population: '5.5M',
    eurovisionWins: 3,
    firstEntry: 1960,
    funFact: 'Norway holds the record for the most last-place finishes in Eurovision, but also produced Alexander Rybak\'s record-breaking 2009 win.',
    famousActs: ['Alexander Rybak', 'Secret Garden', 'Bobbysocks'],
  },
  spain: {
    capital: 'Madrid',
    population: '47M',
    eurovisionWins: 2,
    firstEntry: 1961,
    funFact: 'Spain is one of the "Big Five" and is known for bringing high-energy performances to Eurovision.',
    famousActs: ['Massiel', 'Salomé', 'Chanel'],
  },
  greece: {
    capital: 'Athens',
    population: '10.7M',
    eurovisionWins: 1,
    firstEntry: 1974,
    funFact: 'Greece won Eurovision in 2005 with Helena Paparizou\'s "My Number One" — the first Greek-language entry was in 1977.',
    famousActs: ['Helena Paparizou', 'Sakis Rouvas', 'Eleni Foureira'],
  },
  finland: {
    capital: 'Helsinki',
    population: '5.5M',
    eurovisionWins: 1,
    firstEntry: 1961,
    funFact: 'Finland\'s only win came from Lordi, a hard rock/monster band, shocking audiences across Europe in 2006.',
    famousActs: ['Lordi', 'Käärijä', 'Darude'],
  },
  switzerland: {
    capital: 'Bern',
    population: '8.8M',
    eurovisionWins: 2,
    firstEntry: 1956,
    funFact: 'Switzerland won the very first Eurovision in 1956 with Lys Assia\'s "Refrain".',
    famousActs: ['Lys Assia', 'Céline Dion', 'Nemo'],
  },
  ireland: {
    capital: 'Dublin',
    population: '5.1M',
    eurovisionWins: 7,
    firstEntry: 1965,
    funFact: 'Ireland holds the record for the most Eurovision wins (7) and won 3 years in a row (1992-1994). Riverdance was first performed as a Eurovision interval act!',
    famousActs: ['Johnny Logan', 'Dana', 'Niamh Kavanagh'],
  },
  albania: {
    capital: 'Tirana',
    population: '2.8M',
    eurovisionWins: 0,
    firstEntry: 2004,
    funFact: 'Albania selects its Eurovision entry through "Festivali i Këngës", one of the oldest music festivals in Europe.',
    famousActs: ['Anjeza Shahini', 'Ronela Hajati', 'Elhaida Dani'],
  },
  netherlands: {
    capital: 'Amsterdam',
    population: '17.5M',
    eurovisionWins: 5,
    firstEntry: 1956,
    funFact: 'The Netherlands is a founding member and hosted the first Eurovision in 1956 in Hilversum.',
    famousActs: ['Duncan Laurence', 'Teach-In', 'Joost Klein'],
  },
};

export default COUNTRY_INFO;
